name: Deploy to Artifactory on tag

on:
  push:
    tags:
      - "*"

jobs:
  artifactory_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install packages
        run: |
          pip install wheel
          pip install setuptools
          pip install twine
      - name: build
        run: |
          python setup.py sdist bdist_wheel
      - name: Setup .pypirc
        run: |
          pip config --user set distutils.index-servers local
          pip config --user set local.repository https://filipjasic.jfrog.io/artifactory/api/pypi/default-pypi
          pip config --user set local.username ${{ secrets.EMAIL }}
          pip config --user set local.password ${{ secrets.PASSWORD }}
        if: success()
      - name: Deploy package to Artifactory
        run: twine upload -r local dist/* --config-file $HOME/.config/pip/pip.conf